name: automaton_generator
description: An automaton generator is a code generator (codegen) for use in converter generators, scanners, parsers, final article generators, etc.
version: 2.0.0
homepage: https://github.com/mezoni/automaton_generator
topics:
  - codegen
  - generator
  - state-machine
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  simple_sparse_list: ^0.1.4
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
